#!/bin/sh

echo "$2" > func.txt

PARAMS=${#2}

#gcc -finstrument-functions -g -c -o demo.o demo.c
gcc -finstrument-functions -g -c -o _profiler.o $1

#gcc -c -o trace.o trace.c
#gcc -c -o trace.o trace_20111223.c

if test $PARAMS -eq 0
then
	#gcc -c -o trace.o trace_full.c
	gcc -c -o trace.o trace_full.c
	#gcc -c -o trace.o trace.c
else
	gcc -c -o trace.o trace_specific.c
fi

#gcc demo.o trace.o -o main
gcc _profiler.o trace.o -o main -lm

echo Run with ./main
